### ISSUE TITLE
Certain maps freezing/crashing playfield

### ISSUE THREAD

**Issue by NixXSkate** [FukutoTojido/beatmap-viewer-web#19]
Maps such as [https://preview.tryz.id.vn/?b=26726](url) seem to crash the playfield when playing or scrubbing into the mapped sections.

**Comment by NixXSkate** [comment]
Now I'm getting "TypeError: Cannot read properties of null (reading 'querySelector')" whenever trying to load a map, not sure if it's just currently in development.

**Comment by FukutoTojido** [comment]
This might be a bug in which the web trying to find Argon skin's HitCircleOverlap value on the timeline. It should be fallback to legacy skin correctly now.

Resolved with de2c0172fd9b43af7dfb7095ac21c6c783f7352e

**Comment by FukutoTojido** [comment]
By the way, make sure to clear the cache of the site (pressing Ctrl+Shift+R) to apply the update.

**Comment by FukutoTojido** [comment]
Ah I see. Old maps are missing certain fields in the .osu file. Should be fixed by now.
