### ISSUE TITLE
"Error: File format is not recognized" when loading old beatmaps

### ISSUE THREAD

**Issue by nyaruku** [FukutoTojido/beatmap-viewer-web#28]
https://osu.ppy.sh/beatmapsets/11701#osu/44512 for example

**Comment by FukutoTojido** [comment]
This map is not available for download on osu! website or any of the mirrors. Do you have any more examples or just this beatmap only?

**Comment by nyaruku** [comment]
Oh, i didn't noticed that the map doesn't exist anymore, gonna try out a existing old map later, if it works fine, i will just close the issue.

**Comment by FukutoTojido** [comment]
I guess I'll close this for now since the original issue has been solved. If you have any problem, you should open a new issue instead.
