### ISSUE TITLE
Some weird circle outside the map ?

### ISSUE THREAD

**Issue by nyaruku** [FukutoTojido/beatmap-viewer-web#30]
![image](https://github.com/FukutoTojido/beatmap-viewer-web/assets/38096703/f4078096-b48a-42ab-84e5-97d4253c9fe4)

**Comment by FukutoTojido** [comment]
Hmm, the slider end got completely blown away on HR
I'll have a look on this

**Comment by FukutoTojido** [comment]
Fixed on 39462628554318745df1704cfcf6cf8e704d1edc
Will be merged when I finish migrating to a newer version of PIXI.js
