### ISSUE TITLE
uhhhhh

### ISSUE THREAD

**Issue by nyaruku** [FukutoTojido/beatmap-viewer-web#41]
(chrome) restarting browser/switching renders didnt fixed it, everything fine on firefox
![image](https://github.com/FukutoTojido/beatmap-viewer-web/assets/38096703/bbf54f72-d4bc-44d6-92ba-d95a548d6420)
![image](https://github.com/FukutoTojido/beatmap-viewer-web/assets/38096703/f9d397b8-0416-497c-8e80-de6ed9fbecbb)

**Comment by FukutoTojido** [comment]
Could be a browser-related problem. It's weird that switching to WebGL 2 renderer didn't help.

**Comment by FukutoTojido** [comment]
Runs fine on my machine (Chrome 122.0.6261.112)

![image](https://github.com/FukutoTojido/beatmap-viewer-web/assets/39629922/a2d3eb6e-5fcd-49c8-b705-69be6a784efd)

**Comment by nyaruku** [comment]
> Runs fine on my machine (Chrome 122.0.6261.112)
> 
> ![image](https://github.com/FukutoTojido/beatmap-viewer-web/assets/39629922/a2d3eb6e-5fcd-49c8-b705-69be6a784efd)
> 

let me look further why it broke for me, as I really dont know why

**Comment by nyaruku** [comment]
![image](https://github.com/FukutoTojido/beatmap-viewer-web/assets/38096703/7b0595ac-581c-4845-a4cb-16710ec406c2)
according to console output, it forces "WebGL 2" even when WebGPU is selected, also some warnings pointing to PixiJS

**Comment by FukutoTojido** [comment]
Can I have the output of `chrome://gpu`?

**Comment by nyaruku** [comment]
> Can I have the output of `chrome://gpu`?

[about-gpu-2024-03-10T20-26-13-230Z.txt](https://github.com/FukutoTojido/beatmap-viewer-web/files/14551679/about-gpu-2024-03-10T20-26-13-230Z.txt)

**Comment by nyaruku** [comment]
any news?

**Comment by nyaruku** [comment]
that actually, didn't fixed it

**Comment by FukutoTojido** [comment]
Can you try it on MS Edge instead? I'm not sure if it is Chromium problem or Chrome-specific problem

**Comment by FukutoTojido** [comment]
Hi, any update on this problem?

**Comment by FukutoTojido** [comment]
@nyaruku Hi, any update on this problem?

**Comment by nyaruku** [comment]
> @nyaruku Hi, any update on this problem?
sorry, I total forgot it, let me test it right now, if it's worked in one of the chrome updates that happened a while ago

**Comment by nyaruku** [comment]
![image](https://github.com/user-attachments/assets/2c705220-b564-4cbe-aa5a-7d76a8f77229)
seems to be fixed on chrome
