### ISSUE TITLE
Add mod as search params.

### ISSUE THREAD

**Issue by IkaWaAyuMu** [FukutoTojido/beatmap-viewer-web#42]
Right now, If I want to preview a map with mods (ex. give links to beatmap to specific mods) you have to tell user to turn the mod on manually from settings.

So I purpose to also have search params on mods such as `https://preview.tryz.id.vn/?b=4276057?m=24` means map [`4276057`](https://osu.ppy.sh/beatmapsets/2048051#osu/4276057) with mod `HDHR` pre-applied.

This approach may not support future `lazer` mod as I think they doesn't use bitwise on apiv2 now.

**Comment by FukutoTojido** [comment]
Might be a good idea. Give me some time to implement it

**Comment by FukutoTojido** [comment]
I have just added the mod params by using `?m=<mods_string_combination>`. Since the site only supports HD, HR, DT, EZ, and HT, using mod string instead of mod enum would be less complex.
For example: `https://preview.tryz.id.vn/?b=3939123&m=HDHR`
