### ISSUE TITLE
Applying speed modification mod (`DT` or `HT`) have distorted effect on sound.

### ISSUE THREAD

**Issue by IkaWaAyuMu** [FukutoTojido/beatmap-viewer-web#45]
Applying speed modification mod (`DT` or `HT`) have distorted effect on sound. It will be (likely) cured (without song) later at some interval (or not, did not have thoroughly tested.)

Test subject : https://preview.tryz.id.vn/?b=3465034&m=DT
**Headphone warning** Pain in the ears.

https://github.com/FukutoTojido/beatmap-viewer-web/assets/7066150/722cde96-e11f-4e60-a04c-1a74dedcd39d

Effect still occour if skip to mid song after load (This takes longer to cure)

https://github.com/FukutoTojido/beatmap-viewer-web/assets/7066150/2c5311dc-2389-4f0f-b578-955ef6a97ec2

**Comment by FukutoTojido** [comment]
That's weird. Although some minor artifacts might appear, it shouldn't sound as bad as in the video. What browser are you using?

https://github.com/FukutoTojido/beatmap-viewer-web/assets/39629922/14c3df07-6b72-4627-86fe-27fc597f1c1c

**Comment by IkaWaAyuMu** [comment]
> That's weird. Although some minor artifacts might appear, it shouldn't sound as bad as in the video. What browser are you using?

MS Edge `122.0.2365.80`
Can't try with incognito as it freeze at `Initializing: Default Sample`.

**Comment by FukutoTojido** [comment]
It was freezing because it was at the initial setup. You can try again

**Comment by IkaWaAyuMu** [comment]
> What is your OS then?

Windows `10.0.19045`

**Comment by IkaWaAyuMu** [comment]
> It was freezing because it was at the initial setup. You can try again.

No luck, my ears die.

**Comment by FukutoTojido** [comment]
That is really weird tbh. I think I'm gonna enable Nightcore and Daycore for compatibility.

**Comment by FukutoTojido** [comment]
@IkaWaAyuMu Just added Nightcore and Daycore so you can try if they sound weird or not (DT and HT used a library to avoid pitch shifting so it might be the cause on your machine)

**Comment by IkaWaAyuMu** [comment]
> @IkaWaAyuMu Just added Nightcore and Daycore so you can try if they sound weird or not (DT and HT used a library to avoid pitch shifting so it might be the cause on your machine)

Tried it, works perfectly fine for me.

**Comment by IkaWaAyuMu** [comment]
An update on issue:

If you turn the mod off after playing with those mod applied, the songs keep the speed up (Both `HT` and `DT` have speed **up** effect, but `DT` lasts longer) and skip to some points that not accurate to the map. Seeking will solve the issue.

https://github.com/FukutoTojido/beatmap-viewer-web/assets/7066150/93ee02ec-d326-4b85-81d5-366a6be3f25f


https://github.com/FukutoTojido/beatmap-viewer-web/assets/7066150/baf0c5be-167c-4b00-8dfd-8f9433b5e8f3

**Comment by FukutoTojido** [comment]
I think your device should specifically stick with NC and DC for now. I cannot reproduce this on my end
