### ISSUE TITLE
make it run as fast as tetr.io

### ISSUE THREAD

**Issue by RKevo** [FukutoTojido/beatmap-viewer-web#46]

**Comment by FukutoTojido** [comment]
"Sorry that's the best I could do. 90fps on a Google Pixel 7, 60fps on a Xiaomi Mi Mix 2S, 180fps on a 3050 Laptop.

If you can somehow boost the performance of the site, please do not hesitate to PM me or make a pull request."

Alright it seems you are having some performance issues here. Have you turned on Hardware Acceleration? If so, what is your machine specs? What is the average FPS comparing to your monitor refresh rate also? Is there any app that is GPU intensive which was running in the background?
