### ISSUE TITLE
Just attempted to replace the old player with this one by changing osuplus code.

### ISSUE THREAD

**Issue by Trung0246** [FukutoTojido/beatmap-viewer-web#49]
![image](https://github.com/FukutoTojido/beatmap-viewer-web/assets/11626920/2dab3f19-e747-43dd-9f82-a4d9c73ac68b)
![image](https://github.com/FukutoTojido/beatmap-viewer-web/assets/11626920/1320a198-134c-449a-a18e-08f4fa2aade3)
![image](https://github.com/FukutoTojido/beatmap-viewer-web/assets/11626920/46ab8fd8-6f94-4115-92e2-582b43a939ab)

Literally 3 lines of changes 👌,everything works so far.

**Comment by FukutoTojido** [comment]
Would really be appreciated if this got merged

**Comment by FukutoTojido** [comment]
It is merged today!
