### ISSUE TITLE
Timestamped preview links not loading properly

### ISSUE THREAD

**Issue by MF-JEWM** [FukutoTojido/beatmap-viewer-web#50]
A friend and I have been trying to add functionality to a userscript where Ctrl+Left Clicking the point of failure graph will open a beatmap at the timestamp selected.

When we first worked on the userscript it seemed to work fine, however now we noticed that the timestamp didn't seem to function properly.

After further inspection it seems that this issue occurs regardless of how anyone I've talked with tries to load a timestamped beatmap preview. No matter what timestamp is used the beatmap starts at 0:00 once the loading process completes.

Here is a timestamped preview link to save you searching time:
https://preview.tryz.id.vn?b=4405432&t=55526

I've tried with various browsers, ad block disabled, clearing cookies, etc. I can't seem to get the timestamp feature to function properly when loading a beatmap preview link.

Thanks!

**Comment by FukutoTojido** [comment]
Thank you for noticing me.
I have actually been noticing it for a while but too lazy to fix back then. Will roll out fix in a few days

**Comment by FukutoTojido** [comment]
Fixed in fec1112b23829630ff0b679cfa530ae9ac602b49
