### ISSUE TITLE
InternalError: too much recurson

### ISSUE THREAD

**Issue by Trung0246** [FukutoTojido/beatmap-viewer-web#51]
https://preview.tryz.id.vn/?b=2052199

Unsure what caused it. Probably being Aspire map causing weird slider stuff.

**Comment by FukutoTojido** [comment]
It looks like this is a problem coming from the storyboard where it is trying to catch a RegEx block and this is only happening on Firefox. I guess I'll mark this as won't fix due to browser's nature. Sorry about that.
