### ISSUE TITLE
Typo on "HalfTime" that causes 404 error

### ISSUE THREAD

**Issue by Sheppsu** [FukutoTojido/beatmap-viewer-web#52]
There's a typo somewhere that is "HalfTime" instead of "Halftime," which causes a 404 error (for /static/mods/Halftime.png) and the site is stuck on Initializing.

**Comment by FukutoTojido** [comment]
That's weird, I have updated the file before pushing. Let me have a look

**Comment by FukutoTojido** [comment]
Alright things should be good now. I don't know why the name change wasn't included in the commit
