### ISSUE TITLE
Incorrect stack leniency (possibly only on lower end devices)

### ISSUE THREAD

**Issue by nolife99** [FukutoTojido/beatmap-viewer-web#53]
Here's map id to test: 1487797 (probox candyland top diff)
at 02:54:810, objects should not be stacked that much

have noticed that it rarely works properly, might be a problem with some operations executing before/after when they're supposed to

**Comment by FukutoTojido** [comment]
I actually acknowledge about this bug but haven't got the time to do it. I'll have a look later. Thank you for reminding me.

**Comment by FukutoTojido** [comment]
Found out the reason why. This should be fine now
