### ISSUE TITLE
Parsing 'L' slider with more than 2 control points creates an incorrect slider path

### ISSUE THREAD

**Issue by nolife99** [FukutoTojido/beatmap-viewer-web#54]
Instead of treating each control point as a red anchor on a Linear type slider, each control point is treated as a control point on a bezier curve (basically parsed like a bezier slider)

a good example is probox's exit this earth's atmosphere map 5:29:200, the star sliders are not calculated as expected

**Comment by FukutoTojido** [comment]
I was hardcoding for this type of slider back then. Right now I'm having a rewrite of the slider calculation system so it might take a while to fix.

**Comment by FukutoTojido** [comment]
should be fixed now with the new slider calculator
